BSA_COL = "BSA"
BMI_COL = "BMI"
L_SN_N_COL = "L SN-N"
L_N_IMF_COL = "L N-IMF"
R_SN_N_COL = "R SN-N"
R_N_IMF_COL = "R N-IMF"
SCHNUR_COL = "Schnur scale weight"

L_REMOVED_COL = "L breast"
R_REMOVED_COL = "R breast"
TOTAL_REMOVED_COL = "Total Removed"

SN_N_COL = "SN-N"
N_IMF_COL = "N-IMF"
PER_BREAST_REMOVED_COL = "Removed"
SIDE_COL = "SIDE"
UNIQUE_ID_COL = "MRN"

INPUT_FEATURE_COLS = [BSA_COL, BMI_COL, L_SN_N_COL, L_N_IMF_COL, R_SN_N_COL, R_N_IMF_COL, SCHNUR_COL]
OUTPUT_FEATURE_COLS = [L_REMOVED_COL, R_REMOVED_COL, TOTAL_REMOVED_COL]
FEATURE_COLS = INPUT_FEATURE_COLS + OUTPUT_FEATURE_COLS


TRAIN_FEATURE_COLS = [BSA_COL, BMI_COL, SN_N_COL, N_IMF_COL]
TRAIN_OUTPUT_COLS = [PER_BREAST_REMOVED_COL, TOTAL_REMOVED_COL]
TRAIN_COLS = TRAIN_FEATURE_COLS + TRAIN_OUTPUT_COLS